---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  #- name: debian-7.2.0
    #driver_config:
      #box: debian-7.2.0
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[statsdaemon]
    attributes:
        go:
            owner: 'vagrant'
            group: 'vagrant'
        statsdaemon:
            graphite: '-'
