---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6
    driver_config:
      box: chef/debian-7.6
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
        - recipe[statsdaemon-bitly]
    attributes:
        go:
            owner: 'vagrant'
            group: 'vagrant'
        statsdaemon:
            graphite: '-'
