---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6
    driver_config:
      box: chef/debian-7.6
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-14.10

suites:
  - name: default
    sudo: true
    run_list:
        - recipe[statsdaemon]
    attributes:
        go:
            owner: 'vagrant'
            group: 'vagrant'
        statsdaemon:
            graphite_addr: '-'
            flavor: 'bitly'

  - name: vimeo
    sudo: true
    run_list:
        - recipe[statsdaemon]
    attributes:
        go:
            owner: 'vagrant'
            group: 'vagrant'
        statsdaemon:
            graphite_addr: '-'
            flavor: 'vimeo'
